name: Publish to NPM

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies and run tests
      run: |
        yarn install && npm test

    - name: Configure Git user
      run: |
        git config --global user.email "hassanpudineh67@gmail.com"
        git config --global user.name "hassanpdn"

    - name: Bump release version
      if: startsWith(github.event.inputs.release-type, 'pre') != true
      run: |
        echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
        echo "RELEASE_TAG=latest" >> $GITHUB_ENV
      env:
        RELEASE_TYPE: ${{ github.event.inputs.release-type }}

        # Commit changes
    - name: Commit CHANGELOG.md and package.json changes and create tag
      run: |
        git add "package.json"
        git add "CHANGELOG.md"
        git commit -m "chore: release ${{ env.NEW_VERSION }}"
        git tag ${{ env.NEW_VERSION }}

    # Publish version to public repository
    - name: Publish
      run: yarn publish --verbose --access public --tag ${{ env.RELEASE_TAG }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

    # Push repository changes
    - name: Push changes to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin && git push --tags

    # - name: Publish to NPM registry
    #   if: success() # only publish when tests pass. 
    #   run: | 
    #     npm version patch && npm publish --access public && git push --follow-tags origin main

    # - name: Add tag and version 
    #   run: | 
    #     git tag v1.0.0 && git push origin --tags

        