name: npm-publish
on: 
  push: 
    branches:
      - main 
jobs:
    release:
      name: 🔥 publish
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: node
          uses: actions/setup-node@v3
          with:
              node-version: 14
              registry-url: https://registry.npmjs.org
        - name: Change package.json version
          run: npm version --no-git-tag-version patch
        - name: Commit and push new version
          run: |
              git config --local user.email "hassanpudineh67@gmail.com"
              git config --local user.name "hassanpdn"
              git add package.json
              git commit -m "Updated package.json version"
              git push
        - name: publish
          run: npm publish --access public
          env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}