name: npm-publish
on: 
  push: 
    branches: [main]
jobs:
    release:
      name: 🔥 publish
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 18.x
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: npx semantic-release