name: Publish to NPM

on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies and run tests
      run: |
        yarn install && npm test

    - name: Configure Git user
      run: |
        git config --global user.email "hassanpudineh67@gmail.com"
        git config --global user.name "hassanpdn"

    - name: Publish to NPM registry
      if: success() # only publish when tests pass. 
      run: | 
        npm version patch && npm publish --access public && git push --follow-tags origin main

    - name: Add tag and version 
      run: | 
        git tag v1.0.0 && git push origin --tags

        